language: r

env:
  global:
    secure: T9RKlD12mW0T73K0ZXEuwYTIKDpfsp7rSvt2sJqSZH8BnZwjwO2qkF2PXptTjDDODAOxx3FbkKi5TJn0PJOnh9xty975ahccnflMgnOm78gqlYUWHGwwQiBS3Z2E2eLCdOgzh4MBSDK1dU3jRfWKmlqhxBEtMspf54xgUY9BH3kQDIhzzhn8iNBV1SW7VBqAw3vnszTI/ItFp0rUPC1RKk7Uk305zkdUw8a6fu7+NEludFxLzLJfiUVMbmTtNOpBrdP5jKpeb0rLtQJwRQGJlkLKadQrOjW3ychHr4+oCUfzIV+77yyNyNKmrKd4EY/3rhLKUUl9Bjs5szX625p7zonNx4dnkUOvj7xroBm1QbZ0QEb11tZkULtKA+3VhIDvwA36vKZIE7v9o+kfEwpGcNYHGJqOWSiiL4aREtbf3Al6V2p03BnU1qb+bP1C5EWoXBfCXK5jYuHs6OxAjSxyRN7C1fnBmFZ2HYxwxc0wiN+IugLOHuIIyJjX3S8AGfGlfTsCGkgh1xBTk0STqIWmJSH5u5VrFqIplhwwutVg0VBFNF7dtQIatzjJfWceKIqlW+Z0rNRYXiXskXAwXvxxyXPJ34pgftgYZyqnbdcQL5vJ4J+7MFGle3J5pQzcZl4qKIfGt/8qGwvHooUAomiUBKnwUmmy6p+V9auhEnHvp5U=

addons:
  apt:
    packages:
      - libxml2-dev
      - libproj-dev
      
r_packages:
  - raster
  - rasterVis
  - tmap
  

r_github_packages:
  - rstudio/bookdown
  
install: 
   - Rscript -e "if (!require('ggplot2')) install.packages('ggplot2')"
   - Rscript -e "if (!require('devtools')) install.packages('devtools')"
   - Rscript -e "if (!require('xml2')) install.packages('xml2')"
   - Rscript -e "if (!require('dplyr')) install.packages('dplyr')"
   - Rscript -e "if (!require('tidyr')) install.packages('tidyr')"
   - Rscript -e "if (!require('readr')) install.packages('readr')"
   - Rscript -e "if (!require('bookdown')) devtools::install_github('rstudio/bookdown')"
   - Rscript -e "if (!require('ggmap')) install.packages('ggmap')"
   - Rscript -e "if (!require('rgdal')) install.packages('rgdal')"
   - Rscript -e "if (!require('rgeos')) install.packages('rgeos')"
   - Rscript -e "if (!require('maptools')) install.packages('maptools')"
   
before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files  
